### PR TITLE
Plus upgrade mention Bookmarks alongside Folders

### PR DESCRIPTION
**Pull request by bjtitus**
* Adds "Folders & Bookmarks" instead of just "Folders" to the Plus upgrade screen
* Removes a bunch of unused Plus views and strings

### Logged in
* Use a non-plus account
* Navigate to Profile
* Tap "Account"
* Verify Profile cell shows "Folders & Bookmarks"
* Scroll down to bottom
* Tap "Learn more about Pocket Casts Plus"
* Verify that upgrade screen displays "Folders & Bookmarks" rather than just "Folders"

### New Account
**I don't know that this test is really needed – they are effectively the same view.**
* Create a new account
* Verify that Plus upgrade screen shows "Folders & Bookmarks"

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary. **Unsure if this qualifies. I think it may not so left it out.**
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bjtitus** [comment]
Im happy to split this up but it's mostly deletions that are compile time checked.

**Review by mebarbosa — CHANGES_REQUESTED** [review]
Hey 👋🏽 Thanks for putting this PR!

I think we should update the first benefit too from `Desktop` to `Desktop & web apps` and `Watch Playback` to `Apple Watch & Wear OS apps`

**Review by SergioEstevao — APPROVED** [review]
Code looks good and it's working great.

I leave to you if you want to address @mebarbosa suggestions on this PR.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bjtitus** [comment]
@mebarbosa Thanks! Could you check this again?

There's a line break issue with the new Watch string, but this is similar to existing problems with other languages, so I've filed an issue (https://github.com/Automattic/pocket-casts-ios/issues/1346) and submitted #1347 to fix.

**Review by mebarbosa — APPROVED** [review]

**Pull request merged**
