### PR TITLE
Eoy2024: fix marquee alignment and sizes

### LINKED ISSUE #2398: This screen looks a bit off compared with the specs. In the specs the font-size seems bigger, the vertical spacing between the two lines is shorter and it would be great if we can align the heart icon vertically so it's centered.

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #2250  |  
|:---:|

Fixes #2398  

This PR updates the marquee component to better align text and images and have proper spacing between elements.
I also took the opportunity to move the Marquee component to a separate file and add a preview for easier tweak of parameters.

| 1 | 2 | 3 |
| - | - | - |
| Simulator Screenshot - iPhone 16 Pro - 2024-11-06 at 10 19 22 | Simulator Screenshot - iPhone 16 Pro - 2024-11-06 at 10 17 07 | Simulator Screenshot - iPhone 16 Pro - 2024-11-06 at 10 16 26 |

## To test

1. Star the app
2. Ensure you have the EOY 2024 FF active
3. Go to Profile tab and tap on the EOY 2024 banner
4. Check the Epilogue and empty Ratings screen where the marquee is used
5. If you have Ratings and want emulate empty ratings I suggest changing the check on `Ratings2024Story.swift` line 23.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/63">7.77</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by MiSikora** [comment]
I'm basing my comment only off of the code and the attached screenshots so it might be inaccurate.

* [The Ratings story](https://www.figma.com/design/lH66LwxxgG8btQ8NrM0ldx/Playback?node-id=3070-23272&t=VKF9PnBfDhXMT9J0-4) shows 2 buttons when there are no ratings but there should be no "Share this story" button.

Screenshot 2024-11-06 at 06 56 45

* In the Ending story the texts look like they're a bit cropped at the bottom. You can see this especially with the S letter.

Screenshot 2024-11-06 at 06 57 12

* There's one more screen that uses the marquee effect - [the Plus Interstitial story](https://www.figma.com/design/lH66LwxxgG8btQ8NrM0ldx/Playback?node-id=3054-3956&t=VKF9PnBfDhXMT9J0-4).

Screenshot 2024-11-06 at 06 58 56

**Comment by SergioEstevao** [comment]
@MiSikora thanks for the review, I updated the screenshots with the latest version of the code.
The ratings screen issue was that I was faking the rate numbers to get the screenshot but forgot to update the place where the share button is hidden depending of ratings number.

**Review by danielebogo — APPROVED** [review]
LGTM!

**Pull request merged**
