### PR TITLE
[Library Update] Firebase

### PR DESCRIPTION
**Pull request by leandroalonso**
Part of #1366

## Context

We're updating our libraries in "batches" so we can meet Apple's requirement of including a privacy manifest for SDKs.

This first batch will target `release/7.56` so we can give it a test on the current beta. I'm aiming at 4-5 libs per release.

This PR updates Firebase. However, a lot of Firebase dependencies are listed as needing privacy manifest but haven't added it yet.

## To test

There are two main things we need to test: events and remote feature flags. The app also uses Performance but we're looking into removing that so it's not part of the testing steps.

### Remote Feature Flags

1. Delete the app from your simulator/device
2. Go to `Constants.swift` and change `newPlayerTransitionDefault` to `false`
3. Run the app
4. Go to Profile > Settings > Beta Features
5. ✅ `newPlayerTransition` should be enabled, which means remote feature flags are working as expected

### Events

1. Go to `AnalyticsHelper.swift` and change `private extension AnalyticsHelper` to `extension AnalyticsHelper`
2. On `ProfileViewController.swift` add `AnalyticsHelper.logEvent("testing_testing")` on the end of `viewDidAppear`
3. Run the app
4. Go to profile a few times
5. Put the app on background
6. ✅  Go to [this link](https://console.firebase.google.com/u/0/project/singular-vector-91401/analytics/app/ios:au.com.shiftyjelly.podcasts/overview/reports~2Fdashboard%3Fparams%3D_u.comparisonOption%253Ddisabled%2526_u.date00%253D20231227%2526_u.date01%253D20240124%2526_r..dimension-value%253D%257B%2522dimension%2522%253A%2522eventName%2522%252C%2522value%2522%253A%2522testing_testing%2522%257D&r%3Devents-overview&fpn%3D910146533958), change the date to today and check that the event has been triggered in the past 30 minutes (might take some time)

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by leandroalonso** [comment]
@iangmaia can we disable Danger for draft PRs?

**Comment by iangmaia** [comment]
@leandroalonso:
> @iangmaia can we disable Danger for draft PRs?

Sure -- we can choose to not run it at all on drafts with a condition on the GitHub Action level OR we can prevent some checks running on the `Dangerfile` level (for example, the reviewer check, which isn't even applicable at the state most of the times). What do you think would make more sense?

For example, something like this:

In the GHA workflow `./.github/workflows/run-danger.yml`, to completely prevent the job run:
```diff
jobs:
  dangermattic:
+    if: github.event.pull_request.draft == false
    uses: Automattic/dangermattic/.github/workflows/reusable-run-danger.yml@trunk
    secrets:
      github-token: ${{ secrets.DANGERMATTIC_GITHUB_TOKEN }}
```

In the `Dangerfile`, to prevent a specific check:
```diff
-warn("No reviewers have been set for this PR yet. Please request a review from **@\u2028Automattic/pocket-casts-ios**.") unless requested_reviewers?
+warn("No reviewers have been set for this PR yet. Please request a review from **@\u2028Automattic/pocket-casts-ios**.") unless requested_reviewers? || github.pr_draft?
```

**Review by bjtitus — APPROVED** [review]
✅Feature flags work
✅Analytics worked

Is it expected that there are no `xcprivacy` files yet? Wasn't sure if there should be any from the PR description.

**Comment by leandroalonso** [comment]
> Is it expected that there are no xcprivacy files yet? Wasn't sure if there should be any from the PR description.

Oh, good point! Firebase has it, but a lot of the dependencies haven't. :( So we'll need to re-update it once they add it, I added this information in the main issue: #1366 (which libs have, or haven't)

**Pull request merged**
