### PR TITLE
Playback 2024: Completion Rate + Pay Wall

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #2250 |
|:---:|

Part of #2348 & #2352

### Completion Rate

| | |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/fae9c01e-a7bf-4297-916c-cbeb30935b84"> | <video src="https://github.com/user-attachments/assets/279bd9e0-6eda-4406-939c-32b8aa52b763"> |

### Pay Wall
| | |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/e2939065-f3e9-4ec9-806e-c3a995f4f601"> | <video src="https://github.com/user-attachments/assets/b2f6a5ea-b1a3-4825-a0f3-2d69642923f0"> |

### Paywall
1. Enable the `endOfYear2024` feature flag & restart the app
2. Make sure the account to No Plus
3. Navigate to the Profile and tap Playback 2024 Prompt
4. Navigate through the stories until you hit the Paywall screen
5. Tap the paywall screen to advance to the end
6. Tap the "Check out Pocket Casts Plus" button to open the upsell screen

### Completion Rate Plus

1. Set the account to "Plus" from the Developer menu screen
2. Navigate through the stories until you hit the Completion Rate screen
3. Make sure you see the "Plus" badge

### Completion Rate Patron

1. Set the account to "Patron" from the Developer menu screen
2. Navigate through the stories until you hit the Completion Rate screen
3. Make sure you see the "Patron" badge

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by danielebogo — CHANGES_REQUESTED** [review]
Hey @bjtitus few things while testing:

• Tapping on the button to present the paywall doesn't do anything. It just moves to the next card
• Tapping on the left side of the last card, doesn't navigate to the previous card
• There's a different left margin in the text for this screen:

| Text left margin | Video of the button not responsive and last card |
| -------- | ------- |
| Simulator Screenshot - iPhone 16 - 2024-10-29 at 16 53 38  |  |

**Comment by bjtitus** [comment]
I fixed the interactions on the Pay Wall & Epilogue screens so they should both navigate as well as keep their working buttons.

Also adjusted the spacing about on Listening Time. I will probably come back and adjust all of these and clean the code up later on:

| | |
| -- | -- |
| Simulator Screenshot - iPhone 16 - 2024-10-29 at 12 15 50 | Simulator Screenshot - iPhone 6s - 2024-10-29 at 12 13 57 |

**Review by danielebogo — CHANGES_REQUESTED** [review]
@bjtitus thanks for fixing those points.
I think there's a problem with the bottom padding in the last card

Should the bg be edge to edge?

Simulator Screenshot - iPhone 16 - 2024-10-29 at 19 34 39

**Comment by bjtitus** [comment]
I'll probably unify these footers at some point but it should be fixed up now:

| | |
|--|--|
| Simulator Screenshot - iPhone 16 - 2024-10-29 at 14 16 55 | Simulator Screenshot - iPhone 6s - 2024-10-29 at 14 13 30 |

**Comment by MiSikora** [comment]
Is the percentage in the Completion Rate story in the correct place? I think it should be in the bottom right corner of the black rectangle if it fits and above it if it doesn't.

**Review by danielebogo — APPROVED** [review]
The last card seems fixed!

@MiSikora this is what I see. @bjtitus would you mind checking it as well? I see in Figma the number is bottom/right. I will approve it for now. Let me know if this needs to be fixed here or in a separate PR.

**Comment by bjtitus** [comment]
> I think it should be in the bottom right corner of the black rectangle if it fits and above it if it doesn't.

Sorry, I think my original screenshots are out of date. It's stays outside of the rectangle up to 25% and then switches inside.

**Pull request merged**
