### PR TITLE
[Library Update] Automattic-Tracks-iOS

### LINKED ISSUE #1219: Upgrade `Automattic-Tracks-iOS` to `3.0.0` (or latest)
Howdy! We just released [version `3.0.0`](https://github.com/Automattic/Automattic-Tracks-iOS/releases/tag/3.0.0) of the `Automattic-Tracks-iOS` library. It looks like PCiOS is using version `0.13.0` of the package, so I will let y'all handle doing the upgrade so you can take note of any of the breaking changes from `0.13.0` to `3.0.0`. There shouldn't be too much work to accommodate the upgrade, but I figured it's better for your team to handle it because you'll have a better idea of how to handle those breaking changes. 

`3.0.0` specifically uses the Sentry default for the `releaseName` value, which organizes the releases better across all the projects in our Sentry org. No rush on that, just wanted to let you know.

As always, let Apps Infra know if you have any questions as you go through the upgrade!

### PR DESCRIPTION
**Pull request by leandroalonso**
Part of #1366
Fixes #1219

Update `Automattic-Tracks-iOS` (and by doing so, update `Sentry`).

## To test

1. On `AnalyticsEvent` add a `case testTestTest`
1. On `ProfileViewController.swift` `viewDidAppear` add `Analytics.track(.testTestTest)`
2. Run the app and enter/leave Profile a few times
3. Put the app in the background (so events are sent)
4. ✅ Go to [Tracks](https://mc.a8c.com/tracks/live/?eventname=pcios_test_test_test&user=&useragent=) and check that the event was recorded (it might take ~10 minutes\ to appear)

For Sentry we'll need to wait for a build to be released. However, I'm confident it's working because you can see the new format among Sentry releases.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@spencertransier I did the update of `Automattic-Tracks-iOS` and there was no compatibility issues at all, everything is working. I just want to double-check with you first before moving on about this:

> 3.0.0 specifically uses the Sentry default for the releaseName value, which organizes the releases better across all the projects in our Sentry org. No rush on that, just wanted to let you know.

is there any specific thing I should test for this? I can see an entry on Sentry saying `7.56 (7.65.0.1)`, which is different from the other ones, so I assume it's that?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by spencertransier** [comment]
@leandroalonso It looks like PCiOS hasn't been setting a custom value for the Sentry `releaseName` value, so no other changes are needed to upgrade to version 3.x of Tracks 👍

**Review by bjtitus — APPROVED** [review]
✅ Verified the Tracks logging 👍

**Pull request merged**
