### PR TITLE
Settings Sync: Podcast notification

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #1400 | Depends on #1432 |
|:---:|:---:|

Syncs the Notification podcast setting.

### Authorization

Testing that the iOS authorization prompt is shown on the device which _receives_ the synced settings if it hasn't already been authorized first.

* Delete any installations to clear Push permissions
* Install the app on two devices and log in with the same account
* D1: Navigate to a Podcast settings page
* D1: Enable Notification setting for that podcast
* D1: Pull to refresh from the Podcast list
* D2: Pull to refresh from the Podcast list
* D2: Make sure you are prompted to enable push
* D2: Navigate to the same podcast's settings page
* D2: Check the Notification toggle
* Copy the Device UUID from Settings > Developer > "Copy Device ID"
* Visit the Device list page and search for your device ID
* Verify that the "MESSAGES?" column reflects your notification setting on that device

### Sync

* Install the app on two devices and log in with the same account
* D1: Navigate to a Podcast settings page
* D1: Enable Notification setting for that podcast
* D1: Pull to refresh from the Podcast list
* D2: Pull to refresh from the Podcast list
* D2: Navigate to the same podcast's settings page
* D2: Check the Notification toggle

### Restore

* Install the app on two devices and log in with the same account
* D1: Navigate to a Podcast settings page
* D1: Enable Notification setting for that podcast
* D1: Pull to refresh from the Podcast list
* D2: Pull to refresh from the Podcast list
* D2: Navigate to the same podcast's settings page
* D2: Check the Notification toggle

### Bulk

* Install the app on two devices and log in with the same account
* D1: Navigate to the Notifications settings page
* D1: Go to the "Choose Podcasts" or "X Podcasts Chosen" page
* D1: Select Podcasts and also try "Select All" and "Deselect All" separately
* D1: Pull to refresh from the Podcast list
* D2: Pull to refresh from the Podcast list
* D2: Navigate to the Notifications page and ensure count and selected podcasts matches

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — COMMENTED** [review]
@bjtitus like we talked, this one is probably a bit more involved than just sending/retrieving the settings. I've setup this branch to run on two real devices and synced notifications among them and I'll wait to see if they appear correctly.

However, we do have a few issues:

1. When I ticked a lot of podcasts, one of them was not synced. I'm not sure why, but after I went there, unchecked, checked again, and resynced, it appeared on the other devices
2. Like we talked, we need to ask to enable push notifications if the device don't have it active. Not doing that results in the notifications being shown disabled for all podcasts, and we might run into issues with this logic here:

https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/PodcastManager.swift#L35-L38

These do not necessarily need to be done here. To be honest, I'd leave notifications for later because it's probably more involved.

**Comment by leandroalonso** [comment]
@bjtitus I didn't receive any notifications on any of the devices I set up. :(

I don't think this PR has changed anything but I'll re-run the test before we merge that to make sure everything is working as expected. I think this PR is not a blocker for the remaining tasks, right?

**Comment by bjtitus** [comment]
> I think this PR is not a blocker for the remaining tasks, right?

It's not blocking anything else.

I'll take a deeper look at this today. I didn't see anything else in the client code handling notification registration so maybe something needs to be updated server side?

**Comment by leandroalonso** [comment]
> I didn't see anything else in the client code handling notification registration so maybe something needs to be updated server side?

@bjtitus I think the Xcode build doesn't receive notifications, the issue is not with this PR!

**Review by leandroalonso — COMMENTED** [review]
Ok, so I was finally able to fully test that. The notifications don't work for the device that didn't enable them and I think that is expected.

Why? Because the notifications are not tied to an account. Today, for example, if you have multiple devices logged in to the same account you need to enable the notifications on all of them.

I was wondering if this should be handled by the server or by the client but changing on the server will fundamentally change for all existing devices: if we tie a notification to an account, all of sudden the devices logged in into the same account will start receiving notifications.

I believe that for this to fully work we'll have ensure the server is "informed" when a new podcast notification arrives (either enabling/disabling) it.

@bjtitus Do you prefer to merge this PR and handle everything on other PRs or to put this on hold? The syncing is indeed working (although with some caveats discussed above) but if we're shipping notifications we need to ensure they're working on multiple devices (and tbh I'd leave that to be tackled in the end, after the rest is done).

**Comment by rviljoen** [comment]
@bjtitus @leandroalonso It may be worth looking into this known notification bug: https://github.com/Automattic/pocket-casts-ios/issues/1198. If we do automatically enable notifications on a synced device, or provide the user a popup to enable it, it will probably rely on this bug to be fixed first.

**Comment by leandroalonso** [comment]
@bjtitus is this ready for review? Just want to make sure I don't miss it.

**Comment by bjtitus** [comment]
Nearly! I need to fix an issue with selecting multiple podcasts from the main Notifications settings screen.

Hoping to have it ready later today!

**Comment by bjtitus** [comment]
@leandroalonso Ok! Ready for another look whenever you get a chance. I've updated the instructions to cover several more situations.

Ran into a bit of a snag when using the SQLite json representations. It returns `Int` instead of a `Bool` so I am converting that in https://github.com/Automattic/pocket-casts-ios/pull/1437/commits/a8d30f72e5af3001c4b7c3f7e9c6f4ca9a43c907 which will also affect any other bool property in Podcast settings.

**Review by leandroalonso — APPROVED** [review]
Tested all the mentioned scenarios + the notifications migration to the new settings and it all works as described.

**Pull request merged**
