### PR TITLE
Update the now playing info when player is not seeking

### PR DESCRIPTION
**Pull request by bjtitus**
This was discovered while testing #2141 but is a bit different from the original issue.

The player `seekTo` completion was updating the now playing info but the `else` block (updating the episode timestamp directly without the player's involvement) was not.

## To test

* Play an episode 
* Lock the phone (or navigate to control center) to see the Media Controls
* Pause playback on the lock screen
* Tap the Skip Back button
* Notice that progress is reflected in the progress bar or timestamps

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by danielebogo** [comment]
@bjtitus can we have this targeting our release branch?

**Review by danielebogo — APPROVED** [review]
Thanks @bjtitus 

I tested it and the skip back/forward buttons work now when the Effects player is nil and I'm on the lock screen. I also checked the values and they are reflected in both lock screen and in app.

Just 2 things:
Can we update the changelog?
Can we also target `release/7.73`? So we can start testing it in beta.

**Review by SergioEstevao — APPROVED** [review]
Looking good!

**Pull request merged**
