### PR TITLE
Playback Skipping: Custom Resource Loader with file cache

### LINKED ISSUE #44: Playback: audio skipped
Initially reported p1650892587223279-slack-C02A333D8LQ

**What the listener said:**

> I was just listening to a 2hour podcast and at about 1hr10min it just skipped back to the beginning. Yet the progress bar still showed that the episode was at 1:10!?

It happened when they played the [Biblical Series: Genesis 1 - Chaos & Order episode](https://nodeweb.pocketcasts.com/admin/podcasts/770548/episodes/923869971).

**What has been done so far**

* Enabled Legacy Bluetooth Support
* Disabled Intelligent Playback Resumption
* Noticed this happens on Bluetooth and over phone speakers

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #44 |  
|:---:|

Fixes #44

Implements a custom `AVAssetResourceLoaderDelegate` that as a memory buffer and a file cache. Use the custom delegate to to handle parallel stream and downloads of episode files.

The custom delegate is based on the[ code in this library](https://github.com/sukov/CachingPlayerItem), but adapted to our needs.

The PR is a bit large but as said above the majority of code comes from a separate library, and the core work is done on integrating it.

## To test

- Start the app
- Ensure that you have the FF `streamAndCachePlayingEpisode` active

### Scenario 1 - Start streaming then start download
- Start playing an episode
- While it's playing tap on the download button on episode detail
- Check if the progress circle on episode detail starts showing progress detail for the download
- Check that the download finishes correctly and you can see the final episode size
- Check that playing continues correct

### Scenario 2 - Start downloading then start playing the episode
- Start download an episode, one with larger duration will make it easier to test
- While it's downloading tap on the play button on episode detail
- The progress circle should go back to 0% ( because we started a new download for the export session)
- Check if the progress circle on episode detail continues to show progress detail for the download
- Check that the download finishes correctly and you can see the final episode size
- Check that playing continues correctly

### Scenario 3 - Start downloading, the start playing, then cancel download

- Start download an episode, one with larger duration will make it easier to test
- While it's download tap on the play button on episode detail
- Check if the progress circle on episode detail continues to show progress detail for the download
- In the middle of the download stop the download on episode detail
- Check that playing continues correctly

### Scenario 4 - Start streaming on multiple episodes

- Start playing an episode.
- Start playing another episode before the first one ends
- Resume playing the original episode
- Check that all works correctly in terms of playing sound, and that you only see two `DownloadManager export session: start exporting ... ` in the logs.

### Scenario 5 - Auto-Downloads

- Enable Auto-downloads for items added to UpNext
- Add multiple items to UpNext
- Play one of those items
- See that the download continues ( it may go back in terms of progress, because we are starting a streaming download)
- Wait to see if the download completes
- Now tap play on  another item for the podcast
- Check that the player starts and at the same time download starts ( remember we have auto-downloads for all up next)
- Tap play on another item on the podcast
- Check the previous episode is queued and starts download again
- Check that new item is playing and downloading

### Scenario 6 - Auto-Downloads and AutoPlay

- Enable Auto-downloads for UpNext and Auto-Play episode
- Clean up your UpNext Queue
- Start playing an episode on podcast that has more episodes to play after
- Seek to the end of episode, less some seconds
- Wait for the episode to finish
- Check if the new episode starts and downloads goes correctly

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by danielebogo** [comment]
@SergioEstevao thanks for this PR!

I made the test covering all the scenarios. This is what I found (but perhaps is expected):

1. While testing scenario 1 I got an error:
```
DownloadManager export session: start exporting 8f650b71-6263-4ce1-872a-7495d9b97c27
UpNextSyncTask [createUpNextSyncRequest]: Sync Reason? None
UpNextSyncTask: Syncing Up Next, sending 1 changes, modified time 1728992790718
UpNextSyncTask: server copy matches our copy, no action required
DownloadManager export session: finished with error -> Error Domain=AVFoundationErrorDomain Code=-11843 "Cannot write output file" UserInfo={NSLocalizedRecoverySuggestion=Change the output extension and try again., NSLocalizedDescription=Cannot write output file, NSUnderlyingError=0x600000da2970 {Error Domain=NSOSStatusErrorDomain Code=-16975 "(null)"}}
DownloadManager export session: failed
TracksService sendQueuedEvents completed. Sent 3 events.
Breaking Italy Night didn't need to be updated from cache server
Downloading episode Ep. 28 - Giuseppe Conte, autoDownloadStatus: notSpecified, previousDownloadFailed: false
TracksService sendQueuedEvents completed. Sent 3 events.
saving played up to 29.036933089 for episode Ep. 28 - Giuseppe Conte
```
not sure if it's an expected one. The episode continued to play.

2. Testing scenario 1 and 2 showed that the player get paused while playing and the download finishes.
3. Testing scenario 4 I often get this errors (same error as above)
```
DownloadManager export session: start exporting 90d2497d-f8e8-4f54-8534-8674d5148ac5
DownloadManager export session: finished with error -> Error Domain=AVFoundationErrorDomain Code=-11843 "Cannot write output file" UserInfo={NSLocalizedRecoverySuggestion=Change the output extension and try again., NSLocalizedDescription=Cannot write output file, NSUnderlyingError=0x600000d736c0 {Error Domain=NSOSStatusErrorDomain Code=-16975 "(null)"}}
DownloadManager export session: failed
```

**Comment by SergioEstevao** [comment]
> Testing scenario 1 and 2 showed that the player get paused while playing and the download finishes.

It's expected to detect a small pause on playback when download is complete, because we are switching players and opening the downloaded file.

**Review by danielebogo — APPROVED** [review]

**Review by bjtitus — APPROVED** [review]
✅ I tested streaming, downloading, and switching between episodes

**Comment by pocketcasts** [comment]
<details><summary>Pocket Casts Prototype Build📲 You can test the changes from this Pull Request in <b>Pocket Casts Prototype Build</b> by scanning the QR code below to install the corresponding build.</summary>
<table>
<tr>
  <td rowspan='6' width='260px'></td>
  <td><b>App Name</b></td><td>Pocket Casts Prototype Build Pocket Casts Prototype Build</td>
</tr>
<tr><td><b>Build Number</b></td><td>pr2247-57e9a91</td></tr>
<tr><td><b>Version</b></td><td>7.75</td></tr>
<tr><td><b>Bundle ID</b></td><td>au.com.shiftyjelly.podcasts.prototype</td></tr>
<tr><td><b>Commit</b></td><td>57e9a91cbf385129042a6fd036fe641825ed7143</td></tr>
<tr><td><b>App Center Build</b></td><td><a href='https://install.appcenter.ms/orgs/automattic/apps/Pocket-Casts-Prototype-Builds/releases/36'>Pocket Casts - Prototype Builds #36</a></td></tr>
</table>
<em>Automatticians: You can use our internal self-serve MC tool to give yourself access to App Center if needed.</em>
</details>

**Pull request merged**
