### PR TITLE
CarPlay Star button

### LINKED ISSUE #158: CarPlay: Star Icon is missing when Extra Playback Actions is enabled
### Expected behavior
A star icon should be shown on the Player screen so users can star episodes. This supposed to show once 'Extra Playback Actions' is enabled via the General Settings, since its description mentions: "Adds a mark played and star option to your phone lock
screen and CarPlay."

### Actual behavior

Just a mark played option shows up:
IMG_1782

### Steps to reproduce the behavior

- Go to Settings > General and enable Extra Playback Actions
- Connect to Apple Carplay
- Play a podcast and notice the player screen

### PR DESCRIPTION
**Pull request by bjtitus**
Fixes #158 

Adds the Star button to the CarPlay interface. This button is _not_ gated behind the Extra Playback Options toggle since this is not the lock screen or the Car Play Dashboard.

Couldn't get a screen recording from the actual CarPlay unit, but here's one from the simulator:

https://github.com/Automattic/pocket-casts-ios/assets/3250/3365c07f-b0ea-446c-bf10-ff174c512a30

## To test

* Run the app
* Open CarPlay in I/O > External Displays > CarPlay
* Begin playing episode
* Verify Star button is shown at the bottom
* Verify that tapping the Star button correctly marks episode & fills the icon

**NOTE:** When I tested this, the simulator was not really operating the way I expected (weird playback state issues) but everything worked fine in-car. Also, none of these changes really affect any other functionality.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by SergioEstevao — APPROVED** [review]
Working great.

Just a small note do we need Analytics event for the start button or is already done by the server action of starring something?

**Comment by bjtitus** [comment]
Good catch! I saw that there was an analytics event logged for `episode_starred`, but it looks like the `source` property was missing.

Here's what I see in Now Playing on iPhone:
```
🔵 Tracked: player_shelf_action_tapped ["action": "star_episode", "from": "shelf"]
🔵 Tracked: episode_starred ["episode_uuid": "9da592ed-9a3f-4520-ac33-32795e803bea", "source": "player"]
```

and on CarPlay:
```
🔵 Tracked: episode_starred ["source": "unknown", "episode_uuid": "3759841e-0a17-4e9d-b020-58b5caea2e96"]
```

There's a shared property that must be set before logging to ensure the `source` property is set, as [the "Mark as Played" button](https://github.com/Automattic/pocket-casts-ios/blob/c984732f3fae580bb521157297976d89e0160075/podcasts/CarPlaySceneDelegate.swift#L127) and [Chapters button](https://github.com/Automattic/pocket-casts-ios/blob/c984732f3fae580bb521157297976d89e0160075/podcasts/CarPlaySceneDelegate%2BInteraction.swift#L74) do. I've copied that method for use in the Star button.

After:
```
🔵 Tracked: episode_starred ["source": "carplay", "episode_uuid": "05215628-b738-4142-805d-5666429a41d5"]
```

I don't see anything like the `player_shelf_action_tapped` event, so this single event seems to be the standard approach for the CarPlay buttons at the moment.

**Comment by SergioEstevao** [comment]
All looking good now!

**Pull request merged**
