### PR TITLE
Update Player shelf overflow menu items order

### PR DESCRIPTION
**Pull request by yaelirub**
Changes introduced when the shelf menu was updated to include transcripts logic (https://github.com/Automattic/pocket-casts-ios/pull/2004) and downloads have pushed the Add Bookmark action below the fold, resulting in a 117% drop in Plus promotion views.

This PR changes the order of default menu items to prioritize top actions based on usage. 

## Screenshots
| Before | After | Android |
|:---:|:---:|:---:|
|IMG_BF541769760B-1|Simulator Screenshot - iPhone 16 Pro - 2024-12-08 at 22 57 07|Screenshot_20241208-221103|

## To test

1. Go to Player
2.   Make sure shelf menu items appear as expected
3. Tap on each shelf menu items to make sure they work as expected
4. Make sure over_flow menu items appear as expected and Bookmarks is above the fold in iPhone Pro
5. Tap on each over_flow menu items to make sure they work as expected

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/67">7.79 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bjtitus — APPROVED** [review]
:shipit: 
Looks good to me!

@yaelirub Out of curiosity, would it make any sense to make this modal fullscreen so nothing is below the fold on larger devices? You would still be able to swipe down from any point. One drawback is that the top actions would be farther away from your finger.

**Comment by yaelirub** [comment]
@bjtitus , good question! @david-gonzalez-a8c , wdyt?

**Comment by david-gonzalez-a8c** [comment]
Sounds good to me, worth testing and observing results. I bet some people miss that it's scrollable and this would trivialize that.

**Pull request merged**
