### PR TITLE
Fix #2132: Fix iPad Crash when presenting popover from share button

### LINKED ISSUE #2132: New Sharing Design crashes on iPad when opening System Sheet
### Description

Opening the system sheet on iPad requires a popover presentation which doesn't have a `sourceRect` from the SwiftUI button.

### Step-by-step reproduction instructions

1. Share an Episode
2. Tap "More"
3. 💥

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPad

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #1910 |
|:---:|

Fixes #2132

The popover `sourceRect` was missing and this adds it back in a bit of a hacky way.
Ideally we would switch to the SwiftUI native `ShareLink` view but that comes with a host of challenges with the `Transferable` conformance. When I tested it before, many apps did not accept certain transferable data representations so I'd prefer to continue with the `UIActivityViewController` method for now.

CleanShot 2024-09-04 at 09 27 24@2x

## To test

* Open an Episode on iPad
* Tap the Share button
* Tap the "More" button
* Verify that a popover appears with sharing options

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/58">7.72 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by SergioEstevao — CHANGES_REQUESTED** [review]
The crash is sorted.

But I noticed some issues with positioning when you rotate the device when the popover is visible:

Simulator Screenshot - iPad mini (6th generation) - 2024-09-04 at 17 16 08
Simulator Screenshot - iPad mini (6th generation) - 2024-09-04 at 17 15 44

**Review by SergioEstevao — APPROVED** [review]
:shipit:

**Comment by bjtitus** [comment]
@SergioEstevao Not the greatest solution but I added observation of a published `frame` value to update the layout.

https://github.com/user-attachments/assets/3bd19720-95c0-4f8d-8a01-8de10d6c797f

**Pull request merged**
