### PR TITLE
Only log out user with auth errors

### LINKED ISSUE #913: Only sign out user in case of a 400, 401, or 403 HTTP Code
When calling `/user/token` the app should not log out the user in case the server response is different from 400, 401, or 403 (like a 500, for example).

### PR DESCRIPTION
**Pull request by bjtitus**
Fixes #913

* Changes the `/user/token` and `/user/login` handler to only log out (clean up tokens) on specific 400, 401, and 403 errors.
* Fires the `podcastRefreshFailed` notification when the `RefreshOperation` fails.

## Implementation

I created two new `APIError` types, `TOKEN_DEAUTH` (400, 401) as retryable errors and `PERMISSION_DENIED` (403) for non-retryable. This covers all of the codes from the ticket and probably describes most auth status codes we would encounter.
Alternatives:
* I considered checking the `400..<500` range, but I feel that we should probably be a bit more precise in case something like a 407 proxy error or 408 request timeout is encountered.
* Could just pass through the status code and check directly instead of having new `APIError` types.
* Could define error codes specific to the HTTP status codes and pass those through. I don't think we need this fine grained handling and these error categories seem more specific
* Could add a `TokenError` type to better encapsulate these errors as specific to the token endpoint but I felt this was a bit simpler for now.

#### SSO
* Log in with an SSO account (Google or Apple)
* Set up a script in Proxyman to change the status code for `https://api.pocketcasts.com/user/token` endpoints. Here's a sample
```js
async function onResponse(context, url, request, response) {
  response.statusCode = 500;
  return response;
}
```
* Profile > Settings > Developer > "Corrupt Sync Login Token"
* Go back to Podcasts page
* Refresh
* Verify `500` was returned
* Verify user account was not logged out, although an error message should be shown on refresh
* Change status code to `401`
* Follow same steps above
* Verify user is logged out

#### Email/Password
* Log in with an email/password account
* Set up a script in Proxyman to change the status code for `https://api.pocketcasts.com/user/login` endpoint. Here's a sample
```js
async function onResponse(context, url, request, response) {
  response.statusCode = 500;
  return response;
}
```
* Profile > Settings > Developer > "Corrupt Sync Login Token"
* Go back to Podcasts page
* Refresh
* Verify `500` was returned
* Verify user account was not logged out, although an error message should be shown on refresh
* Change status code to `401`
* Follow same steps above
* Verify user is logged out

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary. **Most Changelog entries appear to be user facing, but I wonder if something like "avoid logging user out on server errors" would make sense here.**
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@bjtitus I think we should also address the code errors when managing auth tokens for password/email.

Right now it fails if the server doesn't return a `200`. This specific part is here: https://github.com/Automattic/pocket-casts-ios/blob/trunk/Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift#L128

In this case, you need to return `500` for the `/user/login` endpoint (yeah, it sucks that we're using different endpoints).

I completely understand if you'd like to tackle this on a different PR.

Alternatively, we can move everything to the new endpoint (which also supports email/password).

**Comment by bjtitus** [comment]
@leandroalonso 

> we can move everything to the new endpoint (which also supports email/password)

You mean moving to the `user/login` endpoint for both [`email` & `password`](https://github.com/Automattic/pocket-casts-ios/blob/94d3e3872e49fa2ae1333116baf8e7f70ab18c11/Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift#L4743-L4745) and [`idToken`](https://github.com/Automattic/pocket-casts-ios/blob/94d3e3872e49fa2ae1333116baf8e7f70ab18c11/Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift#L4741). Still wrapping my head around the APIs, sorry for the confusion!

**Comment by leandroalonso** [comment]
> Still wrapping my head around the APIs, sorry for the confusion!

No worries!

`/user/token` also supports returning a token for a given email/password — this is the "new one". So we can stop using two code paths/apis (one for email/password and the other for SSO).

However, I feel this might end up being more complex than it seems! 🙃

**Comment by bjtitus** [comment]
@leandroalonso I just pushed a set of changes (https://github.com/Automattic/pocket-casts-ios/pull/1351/commits/b7691fb840bd2f17069da5c53c0a3dd06aeecbf8) to produce and pass through the same errors as the `token` endpoint. Could you take a look and give it a try? I've updated the test steps just to be exhaustive.

I did notice while testing this that it seemed that the `RefreshOperation` failure was not checked in `RefreshManager`, causing the refresh control to never reset. I moved the existing notification to the completion block where both `refreshResponse` and the result of `RefreshOperation` have been checked in https://github.com/Automattic/pocket-casts-ios/pull/1351/commits/b9fb6ed7c657a5f036393b580446250f17007f00. Although this particular spot just looks like an oversight, I wonder if a similar thing might happen in other tasks. Do you have any thoughts there?

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/39">7.56</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/39">7.56</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by leandroalonso** [comment]
> I did notice while testing this that it seemed that the RefreshOperation failure was not checked in RefreshManager, causing the refresh control to never reset.

Nice!

> Although this particular spot just looks like an oversight, I wonder if a similar thing might happen in other tasks. Do you have any thoughts there?

Hmm, I don't remember any issues related to this in the other tasks. 🤔 

One final comment — not directly related to your changes: if the refresh token returns a `500`, I can't load new podcasts. However, this already happens in `trunk`, with the difference that the logged-out message is displayed.

The difference here though is that as long as the server is returning `500`, I can't load podcasts. I think this is out of scope for this specific task but I wonder what's the best course of action here would be.

To reproduce that:

1. Have the proxy tool return 500
1. Profile > Settings > Developer > "Corrupt Sync Login Token"
2. Go to Discover
3. Try to load any podcast you never opened before
4. 💥 It will fail every time

**Comment by bjtitus** [comment]
Many of [these](https://github.com/Automattic/pocket-casts-ios/blob/a36022cbaf7b9ca959fa770d43b713dd4e4e9f3e/Modules/Server/Sources/PocketCastsServer/Public/Cache/CacheServerHandler.swift#L121) [calls](https://github.com/Automattic/pocket-casts-ios/blob/a36022cbaf7b9ca959fa770d43b713dd4e4e9f3e/Modules/Server/Sources/PocketCastsServer/Public/Cache/CacheServerHandler.swift#L153) to the Cache server are being made through `TokenHelper.callSecureURL` but, as far as I can tell, they don't need to be authenticated. Would it make sense to bypass the `TokenHelper` for these or is it an oversight that `callSecureURL` shouldn't be blocking this case? Replacing `callSecureURL` with `URLSession.dataTask` seemed to work from my testing but I may be missing something.

Between this and the `RefreshOperation` issue, I wonder if I should put these changes behind a feature flag so we can go ahead and merge but test before a wider release. I feel like more of these problems will pop up. Then I can submit the `CacheServerHandler` and other fixes in a separate PR.

**Comment by leandroalonso** [comment]
> I wonder if I should put these changes behind a feature flag so we can go ahead and merge but test before a wider release. I feel like more of these problems will pop up. Then I can submit the CacheServerHandler and other fixes in a separate PR.

100% agree!

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/39">7.56 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bjtitus** [comment]
Sorry for the delay! This ended up being a little more annoying since the FF code is not available in this module.

I've wrapped these changes (https://github.com/Automattic/pocket-casts-ios/pull/1351/commits/f8ed3e212ea65e7d828912aa4822f66e2164d5df) in a new feature flag (`errorLogoutHandling`) which is passed through with a not-so-great static property on `ServerHelper`. Without touching the flag, the app behaves as it does now, logging the user out with any error. After enabling the flag and restarting the app, 500 errors do not log the user out.

LMK what you think and I'll submit a follow up with the first series of fixes for error handling.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/39">7.56 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@bjtitus I'm having an issue when logging in with username/password:

1. Login with username/password
2. 💥 None of my podcasts are loaded (`Refresh failed: response returned no data, status code 0`)
3. Tap Refresh
4. Then the podcasts are loaded

The behavior is correct if I enable the flag though!

**Comment by bjtitus** [comment]
Looks like I wrapped the early return behind the flag:
CleanShot 2024-01-24 at 08 49 43@2x

I'll look at mocking `TokenHelper` for the next PR.

**Review by leandroalonso — APPROVED** [review]

**Pull request merged**
