### PR TITLE
Transcripts: Fallback to other transcript format if main one fails

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #1848  |  
|:---:|

This PR changes the way transcripts are loaded so that if the preferred format of transcripts is not working correctly, empty or parsing error, we will try to load a different transcript format.

One of the examples of this happening is on the Chaos Radio transcripts where while they an available `vtt` transcript it's empty so we can go for the next on the list that is `podcast index json` format and it will load it.

## To test

- Start the app
- Ensure that you have the `transcripts` and `newShowNotesEndpoint` FF enabled
- Open any episode from [Chaos Radio](https://pca.st/chaosradio)
- Tap Play
- Open the full screen player
- Tap on transcripts
- Check that the transcript information is show correctly

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bjtitus — APPROVED** [review]
:shipit: Show notes loaded for me on several Chaos Radio episodes.

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao while the fallback logic works well, it doesn't work when downloading.

To reproduce:

1. Download any episode from ChaosRadio that you haven't opened the transcript before
2. Once downloaded, turn off-wifi
3. Play it, open transcript
4. 💥An error is displayed

**Comment by SergioEstevao** [comment]
> while the fallback logic works well, it doesn't work when downloading.

@leandroalonso good catch! 

I update the code so it now uses the same code path when downloading the episode. It actually simplifies the code and avoid replication of the same logic.

Give it a look

**Review by leandroalonso — APPROVED** [review]

**Pull request merged**
