### PR TITLE
Referrals: IAP setup

### LINKED ISSUE #2184: IAP setup of referral SKU product

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #2083  |  
|:---:|

Fixes #2184  

This PR updates the IAP code to use a new subscription id specific for referrals.

The logic to process a Referral purchase will be the following:
- If the user never had a subscription before, we will offer them a Introductory Offer with 2 months free
- If the user had a subscription before, but it's not active we will offer them a new subscription with a promotional offer of two 2 months. **NOTE**: This PR is still no implementing the promotional offer because server is not ready yet.
- After the user uses the referral offer he should never be allowed anymore to have any Trial Offer or the Referral Offer again.

| 1 | 2 - Intro Offer |
| - | - |
| Simulator Screenshot - iPhone 16 Pro - 2024-10-07 at 13 24 00 | Simulator Screenshot - iPhone 16 Pro - 2024-10-07 at 13 24 07 

## To test

- Start the app on the device
- Ensure that you the referrals FF enabled
- Ensure that you have Testflight - Sandbox account so you can do fake IAP calls. Ping me if you need help with this.

### Setup:
- Get a referral link from a user with a Plus or Patron account. You can use your current paid account
- Go to Profile
- Tap on Gift icon on the top left
- Tap on Send Guest Pass
- Copy the referral link and save it to the Reminders app
- You will use this link on the following steps
- Log out from the Plus/Patron account

### Scenario 1 - User that never had a subscription before

- The easiest way to setup this is to create a new user account
- Tap on the Referral link obtained on the Setup on the Reminders app
- Check that The Claim referral Guest pass page is opened 
- Tap on Claim Pass
- Check that the IAP flow start and you see the referral Intro Offer
- Purchase it

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/61">7.75</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bjtitus — COMMENTED** [review]
I see the claim and get the sandbox message and everything seems to go through but the app itself isn't showing my Plus membership on either of the two accounts I tried.

I first used a normal apple account and then, on the second try, added a Sandbox test account but neither seemed to update to Plus inside of the app.

Is that expected?

**Comment by SergioEstevao** [comment]
@bjtitus I think the server side is still not ready to validate this new subscription and consider it a Plus. Can you try to connect to staging? Remember to also create a redeem URL using staging!

**Comment by SergioEstevao** [comment]
@bjtitus So I double check with Simon and the referral IAP was not setup properly in our backend so until that is validated the purchase will not be validated in our servers. 
Let's wait until that is sorted to review again.

**Comment by SergioEstevao** [comment]
@bjtitus the IAP setup is now available on Staging so you should be able to complete the purchase through a referral using the Staging scheme. Remember to test in Staging you will also need a staging referral URL. Ping me if you need help creating one.

**Review by bjtitus — APPROVED** [review]
Tested across staging and purchasing worked through my Sandbox account 👍

**Pull request merged**
