### PR TITLE
Move WatchOS project files to single folder/group

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #

This is a follow up o[n the upgrading of the WatchOS project to be a single target](https://github.com/Automattic/pocket-casts-ios/pull/1505).
On this PR I moved the files that were part of the extension inside the main app folder.
I also removed the duplicates image assets that were shared between projects and merged together the assets files in a single file.

## To test

- Start the Watch OS app on a device
- Smoke test the app to see if all assets are showing correctly.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by rviljoen** [comment]
@SergioEstevao I installed a debug version to my watch tonight and noticed that my log was flooded with the following messages:

> [DistantDiscoverySession] <MRAVDistantRoutingDiscoverySession: 0x1852f020> (Companion| - Disabled) Hosted routing connection invalidated...

This happens as soon as you open the Phone Now Playing Screen on the watch and happens regardless of whether something is playing or not. As far as I can tell the app remains fully functional, despite the flood of messages.

Not sure if it relates to the work you've been doing on the Watch App consolidation. Are you seeing these messages on your side? If not then I think it is safe to ignore and probably a build environment issue on my side.

**Comment by SergioEstevao** [comment]
@rviljoen Not seeing this on my tests, @bjtitus can you please double check when you test this PR

**Comment by rviljoen** [comment]
@SergioEstevao Good to hear! Don't waste too much time on this. In order to run the app on the watch, I have to update a bunch of profiles and identifiers (because we do not have access to the official provisioning profile). It is very likely that I may have broken something as part of that process and only noticed it now.

**Review by bjtitus — APPROVED** [review]
:shipit: 

I didn't see the same logs as @rviljoen so I think we're alright here. I did see some other warning logs like the following but I don't think they're new:

```
-[SPRemoteInterface _interfaceControllerClientIDForControllerID:]:2417: ComF: clientIdentifier for interfaceControllerID:3060002 not found. callStack:(
	0   WatchKit                            0x2ddb2e9c D5463B01-5633-3C22-94D7-576BB50AFB47 + 126620
	1   WatchKit                            0x2ddb4468 D5463B01-5633-3C22-94D7-576BB50AFB47 + 132200
	2   WatchKit                            0x2ddac69c spUtils_dispatchAsyncToMainThread + 40
	3   WatchKit                            0x2ddb4214 D5463B01-5633-3C22-94D7-576BB50AFB47 + 131604
	4   WatchKit                            0x2dda3634 D5463B01-5633-3C22-94D7-576BB50AFB47 + 63028
	5   WatchKit                            0x2dda4290 D5463B01-5633-3C22-94D7-576BB50AFB47 + 66192
	6   Pocket Casts Watch App              0x00803324 $s22Pocket_Casts_Watch_App25SourceInterfaceControllerC8plusInfoSo16WKInterfaceLabelCSgvW + 348
	7   Pocket Casts Watch App              0x008030bc $s22Pocket_Casts_Watch_App25SourceInterfaceControllerC8plusInfoSo16WKInterfaceLabelCSgvs + 128
	8   Pocket Casts Watch App              0x00803020 $s22Pocket_Casts_Watch_App25SourceInterfaceControllerC8plusInfoSo16WKInterfaceLabelCSgvsTo + 72
	9   WatchKit                            0x2ddae0d8 D5463B01-5633-3C22-94D7-576BB50AFB47 + 106712
	10  WatchKit                            0x2ddadc04 D5463B01-5633-3C22-94D7-576BB50AFB47 + 105476
	11  Pocket Casts Watch App              0x006bfa2c $s22Pocket_Casts_Watch_App21PCInterfaceControllerCACycfc + 160
	12  Pocket Casts Watch App              0x006bfa74 $s22Pocket_Casts_Watch_App21PCInterfaceControllerCACycfcTo + 20
	13  Pocket Casts Watch App              0x0080782c $s22Pocket_Casts_Watch_App25SourceInterfaceControllerCACycfc + 1012
	14  Pocket Casts Watch App              0x00807878 $s22Pocket_Casts_Watch_App25SourceInterfaceControllerCACycfcTo + 20
```

**Pull request merged**
