### PR TITLE
Download button on player

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: # |  
|:---:|

Fixes #https://github.com/Automattic/pocket-casts-android/issues/1860

Implements a download shelf action on the player

https://github.com/user-attachments/assets/0ae4a135-b494-4963-80f8-378d0a989e24

## To test

1. Start the app
2. Play an episode
3. Open the full screen player
4. Tap on the more(...) button 
5. Tap on Download
6. Check that the download is started/queued
7. Wait for the download to finish
8. Check that the shelf action is changed to `Remove ... `
9. Tap on Remove
10. Check if file is deleted and system skips to next episode on the queue

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by SergioEstevao** [comment]
Version `7.76` has now entered code-freeze, so the milestone of this PR has been updated to `7.77`.

**Review by bjtitus — APPROVED** [review]
Everything looked good in testing. I wonder if we should use the same icon from the Multi-Action menu, though.

| New | Old |
| -- | -- |
| CleanShot 2024-10-28 at 08 53 37@2x | CleanShot 2024-10-28 at 08 53 50@2x |

**Comment by SergioEstevao** [comment]
@bjtitus thanks for the heads up, I was copying what was done on Android by @mebarbosa.

@mebarbosa did the designers on the project commented about this?

**Comment by mebarbosa** [comment]
> @bjtitus thanks for the heads up, I was copying what was done on Android by @mebarbosa.
> 
> @mebarbosa did the designers on the project commented about this?

@SergioEstevao I can't find the slack conversation that I had with our designs when we [tried to fix this issue in the past](https://github.com/Automattic/pocket-casts-android/issues/1860) for Android. From my memory, we picked the same icon that we have in Episode view when is downloaded. But we can also start another slack thread just to double check this

**Pull request merged**
