### PR TITLE
Referrals: update share message

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #2083  |  
|:---:|

Fixes # 

## To test

1. Start the app
2. Login with a Plus or Patron account
3. Go to Profile
4. Tap on the gift icon on the top left
5. Tap on Share Guest Pass
6. Choose email
7. Check to see if you the update message and an image of the guest pass on the email content

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by bjtitus — APPROVED** [review]
LGTM

:shipit:

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/66">7.78</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by SergioEstevao** [comment]
@bjtitus I did some updates because of Twitter and Instagram can you give it another look?

**Review by bjtitus — APPROVED** [review]
👍 Looks good

I tried Tumblr, Instagram, Mastodon, and Twitter.

**Pull request merged**
