### PR TITLE
Playback 2024: Epilogue Screen

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #2250 |
|:---:|

Completes #2323

https://github.com/user-attachments/assets/0eb32463-31e1-4c41-836e-5ec9b58bdf3a

## To test

* Enable the `endOfYear2024` feature flag
* Restart the app
* Tap the "Playback 2024 is here!" cell
* Tap through the stories until you get to the final one and verify it looks correct
* Tap the "Play again" button and make sure it restarts

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/62">7.76</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by SergioEstevao** [comment]
Working well on the iPhone, but on the iPad is not looking great:

| 1 | 2 |
| - | - |
| Simulator Screenshot - iPad (10th generation) - 2024-10-24 at 15 04 50  | Simulator Screenshot - iPad (10th generation) - 2024-10-24 at 15 05 08 |

**Review by SergioEstevao — CHANGES_REQUESTED** [review]
See my iPad comment

**Comment by bjtitus** [comment]
Good catch!

I think the bottom sheet issue stems from [the switch from Materials Bottom Sheet](https://github.com/Automattic/pocket-casts-ios/pull/1472). I've added a custom detent to calculate the height on iOS 16+ and used the large option on iOS 15 so it's still interactive even if it takes up most of the screen.

The second screenshot is as expected on iPad, as far as I can tell. I believe 2023 was also centered in that smaller modal. We don't have iPad specific designs and I think we would end up with way too much space the way these are currently laid out.

LMK if that looks good to you. I could also break out into a separate PR if you think it might require more thorough testing in other spots.

| iPad | iPhone |
| -- | -- |
| Simulator Screenshot - iPad (10th generation) - 2024-10-24 at 16 37 48 | Simulator Screenshot - iPad (6th generation) - 2024-10-24 at 16 56 14 |


### iPhone

| iOS 16+ | iOS 15 |
| -- | -- |
|  |  |

**Review by SergioEstevao — APPROVED** [review]
Thanks for updating for iPad.

**Pull request merged**
