### PR TITLE
Tweak tracks event properties for Categories Redesign

### PR DESCRIPTION
**Pull request by bjtitus**
* This tweaks several properties for the Categories Redesign to match Android (see https://github.com/Automattic/pocket-casts-android/pull/1980)
* Adds better cache clearing for the "Force Reload Discover" developer option

### Basic Navigation

1. Enable `tracksLogging` and `categoriesRedesign` feature flags
2. Go to Discover tab
3. Tap on a tab from the category pills
`🔵 Tracked: discover_category_shown ["id": 3, "name": "Comedy", "region": "us"]`
4. Open the categories sheet by tapping "All Categories"
5. Tap on a category
6. Verify that you see `discover_category_shown` event
`🔵 Tracked: discover_category_shown ["id": 3, "name": "Comedy", "region": "us"]`

7. Tap on a podcast
8. Verify that you see `podcast_screen_shown` with `list_id`
`🔵 Tracked: podcast_screen_shown ["list_id": "category-comedy-us", "uuid": "873e7420-042d-012e-f9a4-00163e1b201c"]`

9. Navigate back from the Podcast page
10. Subscribe to a podcast.
11. Verify that you see `podcast_subscribed` event
`🔵 Tracked: podcast_subscribed ["source": "discover_category", "uuid": "7c388990-aa35-0136-7b93-27f978dac4db"]`

12. Return to Discover by closing the category
13. Tap on any Podcast
14. Verify that you see `podcast_screen_shown` event without `list_id`
`🔵 Tracked: podcast_screen_shown ["uuid": "d571bc10-da42-013c-cb59-0add964e82c5"]`

### Ad Category Tapped

1. Build with `Staging` configuration
2. Enable `tracksLogging` and `categoriesRedesign` feature flags
3. Navigate to the "Sports" category under "All Categories"
4. Tap the Sponsored Podcast atop the categories list
5. Verify that you see the `discover_ad_category_tapped` event
`🔵 Tracked: discover_ad_category_tapped ["promotion_uuid": "8afc50ae-f9a0-4f26-89d3-29d44d760711", "category": "14", "podcast_uuid": "d28ad3a0-9ff4-0132-f234-5f4c86fd3263"]`

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/45">7.62 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — COMMENTED** [review]
@bjtitus it all works as described, I have a few questions though:

* Can the `id` of a category change? Asking because if the answer is yes then we need to find something else that won't change;
* In one event we use `id` for the number and in another `category`. I wonder if that's intentional? Or if we should name them the same thing?

**Comment by bjtitus** [comment]
> In one event we use id for the number and in another category

Personally, I think this makes some sense because the `discover_category_shown` event's `id` is for the category. For the `discover_ad_category_tapped` it seems less clear whether the `id` would be for the ad/sponsored podcast or the category, so it's specified as `category` there. If I was going to change one, it'd be the `discover_category_shown` event but that is an existing event so I'm hesitant to change it.

**Comment by bjtitus** [comment]
> Can the id of a category change?

I checked with @msurdi-a8c and we don't think this ID should change. They match between Prod and Staging.

**Comment by bjtitus** [comment]
I changed `category` to `category_id` and to an integer value in the `discover_ad_category_tapped` event to match Android in https://github.com/Automattic/pocket-casts-android/pull/2030

**Review by leandroalonso — APPROVED** [review]

**Pull request merged**
