### PR TITLE
Referrals: Update guest pass animation

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: #1981  |  
|:---:|

Fixes # 

https://github.com/user-attachments/assets/dba2d1e7-237b-426d-abe7-94b3c4ac2e7a

## To test

1. Start the app on a real device
2. Ensure that you have the referrals FF enabled and using an account with Plus or Patron
3. Open the Profile tab
4. Tap on the gift icon on the top left
5. Check the guest-pass radial blur circles move with the position/motion of the device

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by danielebogo — APPROVED** [review]
it works well! I would let it test to Dom to see if the animation is correct!

**Comment by pocketcasts** [comment]
<details><summary>Pocket Casts Prototype Build📲 You can test the changes from this Pull Request in <b>Pocket Casts Prototype Build</b> by scanning the QR code below to install the corresponding build.</summary>
<table>
<tr>
  <td rowspan='6' width='260px'></td>
  <td><b>App Name</b></td><td>Pocket Casts Prototype Build Pocket Casts Prototype Build</td>
</tr>
<tr><td><b>Build Number</b></td><td>pr2180-8f83d53</td></tr>
<tr><td><b>Version</b></td><td>7.73</td></tr>
<tr><td><b>Bundle ID</b></td><td>au.com.shiftyjelly.podcasts.prototype</td></tr>
<tr><td><b>Commit</b></td><td>8f83d53b28c2e4153f852b0a7e1033898a97cb13</td></tr>
<tr><td><b>App Center Build</b></td><td><a href='https://install.appcenter.ms/orgs/automattic/apps/Pocket-Casts-Prototype-Builds/releases/34'>Pocket Casts - Prototype Builds #34</a></td></tr>
</table>
<em>Automatticians: You can use our internal self-serve MC tool to give yourself access to App Center if needed.</em>
</details>

**Comment by dcamozzi** [comment]
This is looking great @SergioEstevao. One last nitpick, can we slow down the animation just a bit? Then we're good to go!

**Pull request merged**
