### PR TITLE
New icon for prototype builds

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #

This PR changes the icon for prototype builds to make easier to distinguish from the normal build

## To test

 - Install the prototype build using the QR code on this PR
 - Check that the icon is the electric blue one.
 - Install a debug build using the code in this branch and check that you get the original PocketCast icon

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by pocketcasts** [comment]
<details><summary>Pocket Casts Prototype Build📲 You can test the changes from this Pull Request in <b>Pocket Casts Prototype Build</b> by scanning the QR code below to install the corresponding build.</summary>
<table>
<tr>
  <td rowspan='6' width='260px'></td>
  <td><b>App Name</b></td><td>Pocket Casts Prototype Build Pocket Casts Prototype Build</td>
</tr>
<tr><td><b>Build Number</b></td><td>pr1835-0807a38</td></tr>
<tr><td><b>Version</b></td><td>7.66</td></tr>
<tr><td><b>Bundle ID</b></td><td>au.com.shiftyjelly.podcasts.prototype</td></tr>
<tr><td><b>Commit</b></td><td>0807a38bce371ca66c170704a898dab63ef7b2f3</td></tr>
<tr><td><b>App Center Build</b></td><td><a href='https://install.appcenter.ms/orgs/automattic/apps/Pocket-Casts-Prototype-Builds/releases/15'>Pocket Casts - Prototype Builds #15</a></td></tr>
</table>
<em>Automatticians: You can use our internal self-serve MC tool to give yourself access to App Center if needed.</em>
</details>

**Review by leandroalonso — COMMENTED** [review]
Tested and it works as expected but there's something driving me crazy. Xcode is now showing the electric icon as the default for all targets:

Screenshot 2024-06-18 at 14 45 42

I wonder if there's any configuration we can do so it displays correctly?

**Comment by SergioEstevao** [comment]
> Tested and it works as expected but there's something driving me crazy. Xcode is now showing the electric icon as the default for all targets:

The same happened to me I thought it was just me because I tested it first with the Debug build, it must be a cache issue I will investigate to see if there is a way to reset it.

**Comment by SergioEstevao** [comment]
@leandroalonso I was able to sort it out, needed to change the name of the new icon asset so it shows second in the AppIcon list.
After that you just need to build and close Xcode and open it again and you should see the classic icon on the scheme.

**Comment by SergioEstevao** [comment]
@leandroalonso or maybe not... after another build and it's showing again... this must be cursed!

**Comment by SergioEstevao** [comment]
@leandroalonso I think it's now sorted, from my tests Xcode was giving priority to the other icon because it had sizes nearer to the size of the icon in Xcode.
Now both are universal icon with the same size, and the red one has the name to be the first on the Asset file.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/53">7.67</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — APPROVED** [review]
@SergioEstevao nice!! Thanks for fixing this small thing!

Good to go.

**Pull request merged**
