### PR TITLE
[Kids Profile] Add Tracks events

### LINKED ISSUE #1940: [Kids profile] Add Tracks

### PR DESCRIPTION
**Pull request by danielebogo**
| 📘 Part of: #1935
|:---:|

Fixes #1940 

Tracks events added to the Kids Profile

## To test

> [!NOTE]
> Make sure `kidsProfile` feature is enabled

• Run the app and go to your profile
• You should see the Kids profile banner (if not check the FF panel or reset your user defaults)
• You shuld see `🔵 Tracked: kids_profile_banner_seen`
• Tap on `Request Early Access`
• You should see `🔵 Tracked: kids_profile_early_access_requested`
• You should see `🔵 Tracked: kids_profile_thank_you_for_your_interest_seen`
• If you tap on NO, you should see `🔵 Tracked: kids_profile_no_thank_you_tapped`
• If you tap on Send Feedback, You should see `🔵 Tracked: kids_profile_send_feedback_tapped`
• The text editor should appear and you should see `🔵 Tracked: kids_profile_feedback_form_seen`
• If you tap on Send you should see `🔵 Tracked: kids_profile_feedback_sent`
• If you tap on the `X` in the top right of the banner to dismiss it, you should see `🔵 Tracked: kids_profile_banner_dismissed`

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/56">7.70</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — CHANGES_REQUESTED** [review]
I just had an issue with this testing step:

> • If you tap on the X in the top right of the banner to dismiss it, you should see 🔵 Tracked: kids_profile_banner_dismissed

I don't see any "X" and when dismissing the screen through swipe down the event is not tracked. Here's a screenshot:

**Comment by danielebogo** [comment]
> If you tap on the X in the top right of the banner to dismiss it, you should see 🔵 Tracked: kids_profile_banner_dismissed

@leandroalonso sorry I should have specified this better. This is on the banner in the profile view controller

Screenshot 2024-08-05 at 16 00 25

> when dismissing the screen through swipe down the event is not tracked.

We don't actually track this, only the button. I will ping Duda to check the event and keep both client aligned. In case I'll made a separate ticket to it.

**Review by leandroalonso — APPROVED** [review]
@danielebogo  Ohhh, I was confused by the testing steps hehe

All good!

**Pull request merged**
