### PR TITLE
SSO: Sonos

### PR DESCRIPTION
**Pull request by leandroalonso**
| 📘 Project: #381 |
|:---:|

Update the Sonos screen to use the new login screens with Apple/Google SSO login.

## To test

2. Go to `podcasts` scheme and change Build Configuration to `Staging`
3. On the app, go to Settings > Beta Features > enable `signInWithApple`
3. Add a breakpoint on `SonosLinkController` line `93`

### Username/password

2. Launch the app
3. Sign out if you're signed in
4. In Safari go to: `pktc://applink/sonos/sonos://`
5. Pocket Casts should appear, tap the Continue button
8. Log in with an existing email/password account
9. ✅ Verify after logging in you are returned to the Sonos view and the button says "CONNECT"
9. Tap CONNECT
9. ✅ The breakpoint is hit and the generated URL contains a token

### Apple SSO

3. Sign out if you're signed in
4. In Safari go to: `pktc://applink/sonos/sonos://`
5. Pocket Casts should appear, tap the Continue button
8. Log in with Apple
9. ✅ Verify after logging in you are returned to the Sonos view and the button says "CONNECT"
9. Tap CONNECT
9. ✅ The breakpoint is hit and the generated URL contains a token

### Google SSO

3. Sign out if you're signed in
4. In Safari go to: `pktc://applink/sonos/sonos://`
5. Pocket Casts should appear, tap the Continue button
8. Log in with Google
9. ✅ Verify after logging in you are returned to the Sonos view and the button says "CONNECT"
9. Tap CONNECT
9. ✅ The breakpoint is hit and the generated URL contains a token

### Create account

3. Sign out if you're signed in
4. In Safari go to: `pktc://applink/sonos/sonos://`
5. Pocket Casts should appear, tap the Continue button
8. Create an account (using any method)
9. ✅ Verify after logging in you are returned to the Sonos view and the button says "CONNECT"
9. Tap CONNECT
9. ✅ The breakpoint is hit and the generated URL contains a token

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@geekygecko can I get your 👀 on this too? The logic is practically the same as the username/password, all we do is pass the token to Sonos through a deep link.

However, I don't have a Sonos device to test, so I want to ensure everything is good.

**Review by emilylaguna — CHANGES_REQUESTED** [review]
I gave this a test using the steps, and having the Sonos app installed (but not setup since I don't have a Sonos device) and I confirmed that once I logged in and tapped connect the Sonos app opened correctly. 

I did notice that if I created an account (either due to SSO, or normally) the user is brought out of the Sonos flow and then dropped back into the app.

I came up with an idea on how we can leverage the OnboardingFlow to accomplish the same thing for both new accounts and existing logins and pushed it up here:

https://github.com/Automattic/pocket-casts-ios/compare/issue/381-sonos-sso...idea/381-sonos-sso

Let me know what you think.

**Comment by leandroalonso** [comment]
@emilylaguna I liked this change, can you please merge it into this PR?

**Comment by emilylaguna** [comment]
@leandroalonso Done!

**Comment by leandroalonso** [comment]
@emilylaguna give it a try with creating account and works just fine, as soon as you approve I'm gonna merge it.

**Review by emilylaguna — APPROVED** [review]

**Comment by geekygecko** [comment]
> can I get your 👀 on this too? 

@leandroalonso sorry I didn't get a chance to do this. I have been caught up in the episode search deadline.

**Comment by leandroalonso** [comment]
@geekygecko No worries! It would still be good to test this on a real device though and make sure it's working properly :)

**Pull request merged**
