### PR TITLE
Reimagine Sharing: Enable feature flag

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #1910 |
|:---:|

Just enables the `newSharing` flag by default

## To test

Easiest way to test is to check for the "Clip" option which is new.

### Podcast
* Share from the Podcast detail page
* Verify that the "Clip" option shows up in the list

### Episode
* Share from the Episode detail page
* Verify that the "Clip" option shows up in the list

### Now Playing
* Share from Now Playing
* Verify that the "Clip" option shows up in the list

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/58">7.72 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by danielebogo — APPROVED** [review]
All good!
Just to be 100% sure:
> Podcast
> Share from the Podcast detail page
> Verify that the "Clip" option shows up in the list

I believe that here I should see the new podcast share screen and not Clip right?

**Comment by bjtitus** [comment]
Sorry, I should have been more clear. If the "Clip" option shows up in the sharing list then the flag is enabled. Tapping any of the options should bring up the new sharing screen, yes.

**Comment by danielebogo** [comment]
> Sorry, I should have been more clear. If the "Clip" option shows up in the sharing list then the flag is enabled. Tapping any of the options should bring up the new sharing screen, yes.

Thanks for confirming it! :shipit:

**Pull request merged**
