### PR TITLE
[Deselect Chapters] Sync

### PR DESCRIPTION
**Pull request by leandroalonso**
| 📘 Part of: #1396 |
|:---:|

Adds sync to the chapter deselection.

These are podcasts with chapters you can use to test:

* Clublife: https://pca.st/rLzZCv
* ATP: https://pca.st/accidentaltech

## To test

Please test on **Staging**.

Before starting, gift your test account Patron. Also, go to `FeatureFlag.swift` and change `deselectChapters` to `true`. That will make things way easier. :)

### Basic Sync

1. Login to an account with Patron
2. Play an episode with chapters
3. Go to Chapters, tap "Skip Chapters"
4. Deselect a few chapters
5. Tap Done
6. Dismiss the player
7. Go to Profile > Refresh Now (or pull to refresh)
8. Delete the app
9. Reinstall
10. Login to the same account
11. Play the episode that was playing (needed so chapters are displayed)
12. ✅ Your previously deselected chapters should be deselected

### Multi-device sync

D1 is device 1, D2 is device 2.

1. Login to the same account with Patron on both devices
2. D1: Play an episode with chapters in
3. Go to Chapters, tap "Skip Chapters"
4. Deselect a few chapters
5. Tap Done
6. Dismiss the player
7. Go to Profile > Refresh Now (or pull to refresh)
8. On D2, go to Profile > Refresh Now (or pull to refresh)
9. Open the Player and go to Chapters (you might need to play the episode so chapters appear)
10. ✅ Your deselected chapters on D1 should reflect on D2

You can play with this by changing chapters in one and checking if it's reflected on the other after updating.

### Syncing episode not in Up Next

D1 is device 1, D2 is device 2.

1. Login to the same account with Patron on both devices
2. D1: Play an episode with chapters in
3. Go to Chapters, tap "Skip Chapters"
4. Deselect a few chapters
5. Tap Done
6. Dismiss the player
8. Tap and hold on the miniplayer and tap "Close and clear Up Next"
8. Go to Profile > Refresh Now (or pull to refresh)
9. On D2, go to Profile > Refresh Now (or pull to refresh)
10. Go to Listening History and find the episode that was playing
11. Play it
12. ✅ Your deselected chapters on D1 should reflect on D2

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bjtitus** [comment]
✅Verified single device sync - not sure about this
✅Verified Multi-Device Sync
✅Verified syncing episode not in Up Next

:shipit: Really nice!

**Review by bjtitus — APPROVED** [review]
✅Verified single device sync - not sure about this
✅Verified Multi-Device Sync
✅Verified syncing episode not in Up Next

:shipit: Really nice!

**Pull request merged**
