### PR TITLE
Show all sorting options for episode

### PR DESCRIPTION
**Pull request by SergioEstevao**
| 📘 Part of: # |  
|:---:|

This PR enables showing all available options for episode sorting by adding TitleAtoZ and TitleZtoA.
This will match the sort options in Android and Web

## To test

1. Start the app
2. Open a Podcast
3. Tap on the ... button
4. Select the Sort row
5. Check if you see the options to sort for TitleAtoZ and TitleZtoA
6. Select each of the sorts and see if they sort correctly

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by SergioEstevao** [comment]
@bjtitus can you have into this PR and see why the episode sort options don't update when the `newSettingsStorage` FF is enabled.

**Comment by bjtitus** [comment]
@SergioEstevao I believe `newSettingsStorage` isn't working here because the column was [removed in this revert](https://github.com/Automattic/pocket-casts-ios/pull/1694) during our performance investigations back in May. I think we shouldn't worry too much about that feature flag at the moment.

**Review by bjtitus — APPROVED** [review]
✅ Verified that old setting persists after upgrading to this
✅ Verified new sort options

**Pull request merged**
