### PR TITLE
Settings Sync: Add files settings

### PR DESCRIPTION
**Pull request by bjtitus**
| 📘 Part of: #1400 |
|:---:|

Adds settings for files "Auto Add to Up Next", "Delete Local Files" and "Delete Cloud Files" after playing.

## To test

1. Log in with a Plus account on two devices/simulators (or enable plus in settings, although this will need to be done each time before you view settings - doesn't affect syncing).
2. D1: Navigate to Profile > Settings > Files
3. D1: Change one of the first three options, "Auto Add to Up Next", "Delete Local Files" or "Delete Cloud Files" after playing.
5. D1: Navigate back to the Profile and pull to refresh
7. D2: Pull to Refresh on Podcasts list or Profile
8. D2: Navigate to Profile > Settings > Files
9. D2: Verify that settings toggles show the proper values

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by SergioEstevao — APPROVED** [review]
:shipit:

**Comment by emdashcodes** [comment]
@bjtitus I wanted to test this against my changes on web so I can record a demo video, but for some reason I can't get these ones to sync on the branch like I can with other settings (such intelligent resumption). Am I missing something? I have the simulator pointing towards staging.

**Comment by bjtitus** [comment]
@justinshreve 🤔 I'm not sure what might be going on. Here's a recording showing the sync with the request & response:

https://github.com/Automattic/pocket-casts-ios/assets/3250/7344a9d5-f763-465e-9410-57e3f67d9b70

**Pull request merged**
