### PR TITLE
[Up Next Shuffle] Add shuffle and Clear buttons

### LINKED ISSUE #2320: Add Shuffle Button to Up Next
Add shuffle button to Up Next: KjyDLK1DPPg3snPBMVGWHw-fi-0_1

### PR DESCRIPTION
**Pull request by danielebogo**
| 📘 Part of: [Up Next Shuffle project](https://github.com/orgs/Automattic/projects/1179/views/1)
|:---:|

Fixes #2320 

This Pr adds the new shuffle button instead of the clear queue button. Also adds the Clear left navigation item instead.

| Before | After |
| -------- | ------- |
| Simulator Screenshot - iPhone 16 - 2024-10-22 at 18 37 17 | Simulator Screenshot - iPhone 16 - 2024-10-22 at 18 36 43 |

| Disabled with one item playing | Disabled no items |
| -------- | ------- |
| Simulator Screenshot - iPhone 16 - 2024-10-22 at 18 46 44 | Simulator Screenshot - iPhone 16 - 2024-10-22 at 18 46 57 |

## To test

• CI must be 🟢 
• Run the app and enable the `upNextShuffle` feature flag.
• Restart the app

### Test Up Next in tab
• Add some items into the queue
• Navigate to Up Next
• Check you see the new buttons
• Tapping the shuffle button. Make sure the button changes states (selected/unselected).
• Make sure the button icon also updates
• Close the app and restart
• Make sure it keeps and apply the last button state
• Tap on clear to prompt the modal and clear the queue
• If there's at least one episode playing, you should see the shuffle button disabled
• re adding the new item in the queue should re-enable the button
• test multiple selection works as before
• test it also on different themes

### Test Up Next swiping up
• The shuffle button behave as before
• you should not see the Clear navigation button top left, bbut the Done instead 
• Do the same test as before
• test multiple selection works as before
• test it also on different themes

### Test with FF off
• Switch off the FF
• re run the app
• make sure the app behaves like before

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by SergioEstevao — CHANGES_REQUESTED** [review]
I found issue when updating the shuffle button on the UpNext modal view and then going back to the tab view. The state is not correctly updated.

Here is a video:

https://github.com/user-attachments/assets/7b2d73f7-b062-4594-9160-4825659ac11a

**Comment by danielebogo** [comment]
@SergioEstevao ready for another 👀

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/62">7.76</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by SergioEstevao — APPROVED** [review]
Looking good! :shipit:

**Pull request merged**
