### PR TITLE
[Deselect Chapters] Design

### PR DESCRIPTION
**Pull request by leandroalonso**
| 📘 Part of: #1396 | 🎨 [Designs](https://www.figma.com/file/hHFpI1RtnW4TRb448Q4Don/Player?type=design&node-id=4383%3A26935&mode=design&t=3kwjoLnHImygBNhh-1) |
|:---:|:---:|

Implements the final design of deselecting chapters and adds a few tweaks.

These are podcasts with chapters you can use to test:

* Clublife: https://pca.st/rLzZCv
* ATP: https://pca.st/accidentaltech

## To test

1. Go to Profile > Settings > Beta Features > `deselectChapters` and turn it on
2. Go to Profile > Settings > Developer > Set to Paid Patron
3. Play any episode with chapters
4. Open the player and go to Chapters
5. Toggle the chapter selection
6. ✅ Compare what you see with the designs in Figma
7. Deselect the chapter that is currently being played
8. Tap "Done"
9. ✅ The current chapter should skip
10. Toggle the chapter selection
11. Deselect all chapters
12. ✅ On the latest selected chapter you should see a message when you try to deselect
13. Select again a few chapters
14. Tap "Done"
15. Tap any chapter
16. ✅ The correct chapter should be played

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by bjtitus — APPROVED** [review]
:shipit: Screen looks good!

One thing I noticed is that it's a bit slow to skip to the next chapter if I've deselected the currently playing one and continue playback. I don't think that's anything new in this PR but thought I'd mention it.

**Comment by rviljoen** [comment]
@leandroalonso One small thing I have noticed while testing this. When you go into Chapter Edit mode, the chapter link/URL (if they exist) is hidden, but if you click on the spot where the URL icon is it still opens the link. Hope this makes sense!

**Comment by leandroalonso** [comment]
@rviljoen Thanks for spotting that! Could you please share the episode you saw this behavior? Thanks!

**Comment by rviljoen** [comment]
@leandroalonso Most recent ATP

**Comment by leandroalonso** [comment]
Thanks!

**Pull request merged**
