### PR TITLE
Revert: hidden chapters

### PR DESCRIPTION
**Pull request by leandroalonso**
With the changes made in #553 we had a regression in which podcasts that used to show chapters didn't display them anymore (eg.: Tiesto - Clublife). That includes showing the "Chapters" tab and all related UI stuff (progress of chapter, arrows, etc).

This PR reverts this change to restore the previous feature while we fix it.

## To test

1. Run the app
2. Search for Clublife
3. Play any episode
4. ✅ You should see the "Chapters" tab
5. Tap on it
6. ✅ You should see the current chapter progress

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by jleandroperez — APPROVED** [review]
:shipit:

**Comment by maarut** [comment]
Is there a link to the podcast, or mp3 file so that I can test? searching for Tiesto - Clublife in the podcast directory yielded a lot of results. It could be an authoring issue.

**Comment by maarut** [comment]
Could I have the opportunity to try and investigate and fix the issue before the change is reverted?

**Comment by leandroalonso** [comment]
@maarut the change is reverted in the current beta version — which will be submitted to Apple at the end of next week (normally Friday at the beginning of the day).

If we manage to fix it before, this won't be reverted in production (aka App Store). If you come up with any fix, please feel free to target `release/7.40`.

I'd love to help with this but I have some other priorities. I'm more than happy to help with reviewing and testing any solution though. :)

**Comment by maarut** [comment]
I think this reversion is in error. In investigating the issue, it looks as though the podcast in question (Tiesto - Clublife) is authoring the MP3's with chapters, but marking them all as hidden. To fix the issue, opposes the enhancement submitted as part of #553 .

I can try to enable chapters where all chapters in the table of contents are hidden. Although not ideal, this may be a good middle ground solution.

**Comment by leandroalonso** [comment]
@maarut

> it looks as though the podcast in question (Tiesto - Clublife) is authoring the MP3's with chapters

This is true. Unfortunately, this is common with other podcasts too. The problem is that the regular user perceives this as a bug: something that used to work doesn't work anymore —even though your original PR added an amazing new enhancement.

Also, this is the behavior in the Mac and Android apps, so we need to keep it consistent.

> I can try to enable chapters where all chapters in the table of contents are hidden. Although not ideal, this may be a good middle ground solution.

I tried that! I think it's probably the best solution here.

But, as stated in my comment, [there are a few bugs](https://github.com/Automattic/pocket-casts-ios/pull/553#issuecomment-1570705058): chapters progress and chapters control are not being shown by just enabling it. Here's a screenshot of what I'm referring to:

| Player chapter controls | Chapter progress indicator |
| ----------------------- | --------------------------- |
| Simulator Screen Shot - iPhone 14 - 2023-06-02 at 10 48 30 | Simulator Screen Shot - iPhone 14 - 2023-06-02 at 10 48 35 |

**Comment by maarut** [comment]
@leandroalonso 
> @maarut
> 
> > it looks as though the podcast in question (Tiesto - Clublife) is authoring the MP3's with chapters
> 
> This is true. Unfortunately, this is common with other podcasts too. The problem is that the regular user perceives this as a bug: something that used to work doesn't work anymore —even though your original PR added an amazing new enhancement.
> 
> Also, this is the behavior in the Mac and Android apps, so we need to keep it consistent.
> 

Understood, and also the reason why I mentioned the middle ground solution.

> > I can try to enable chapters where all chapters in the table of contents are hidden. Although not ideal, this may be a good middle ground solution.
> 
> I tried that! I think it's probably the best solution here.
> 
> But, as stated in my comment, [there are a few bugs](https://github.com/Automattic/pocket-casts-ios/pull/553#issuecomment-1570705058): chapters progress and chapters control are not being shown by just enabling it. Here's a screenshot of what I'm referring to:
> 
> Player chapter controls	Chapter progress indicator
> Simulator Screen Shot - iPhone 14 - 2023-06-02 at 10 48 30	Simulator Screen Shot - iPhone 14 - 2023-06-02 at 10 48 35

I have authored a fix that re-instates the previous behaviour for this podcast. Please could you submit other podcasts that also exhibit this behaviour for testing? Thanks

**Comment by leandroalonso** [comment]
@maarut sure thing! Here it is:

* https://pca.st/ylNQ
* https://pca.st/3i8ff6fj

Let me know if you need more. :)

**Comment by maarut** [comment]
Thanks. I've tested both, and the first is working with my fix. The second (I tested a couple of recent episodes from May 2023) didn't exhibit any regressions.

I will raise a PR against release/7.40 shortly [EDIT: PR #888 raised].

**Pull request merged**
