### PR TITLE
Adds a way to export the database and preferences from the Help & Feedback page

### PR DESCRIPTION
**Pull request by emilylaguna**
This adds a button that will export and allow sharing of a zip file that contains the podcast database and UserDefaults.

The process to share the file is:
1. Creating a temporary directory
2. Copying the database into it
3. Copying the preferences file into it
4. Using the NSFileCoordinator to generate a zip
5. Saving the resulting zip to the temporary directory
6. Sharing it
7. Deleting the temporary files after sharing

**Note:** When sharing the system shows some warnings, but doesn't stop us sharing the file. I tried a lot of things to get this to stop, but none worked. 

## Demo Video

https://github.com/Automattic/pocket-casts-ios/assets/793774/f0a722ab-df08-4e20-9ddb-afdad425d1b5

## To test
1. Launch the app
2. Go to the Profile tab
3. Tap on Help & Feedback
4. Tap the Share button in the top corner
5. ✅ You should see the exporting message
6. ✅ After a few seconds you should see the share sheet with the file name "Pocket Casts Export"
7. Share the file to your Mac
8. Open it
9. ✅ Verify it unzips
10. ✅ Verify it contains both the database and preferences files
11. ✅ Verify the database is valid
12. ✅ Verify the preferences are valid

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Review by leandroalonso — COMMENTED** [review]
@emilylaguna works as described! I also did some additional tests to make sure the latest database state is correctly exported.

One small suggestion though: the icon is not super clear to me (I can say the same about the other one), so maybe we should add a "..." button that opens a menu?

Of course not a blocker for this PR.

**Comment by emilylaguna** [comment]
Good idea. I moved them in to a more menu.

**Review by leandroalonso — APPROVED** [review]
I know it's not part of this PR but I wonder if we can change "Status Page" to "System/Connection Status" (as it tests our services and the user's connection).

Other than that, good to go!

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/37">7.54</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/37">7.54</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/37">7.54</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
