### PR TITLE
Cleanup build warnings

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR cleans up a series of build warning that are shown by Xcode, so we don't ignore valid warnings :)

## To test

- CI should be green
- Build and run the app locally and see if you only see two warnings
- Smoke test the main app and the watch OS app
- On the iOS app go to Profile -> Settings and check if the icon for Notification (a bell) is shown
- On the watch app go to Now Playing and if you have more that 9 items on the UpNext queue you should the 9+ icon on the bottom right

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — CHANGES_REQUESTED** [review]
@SergioEstevao I'm seeing these warnings:

Screenshot 2024-03-25 at 18 02 06

Are those expected? Other than that all good

**Comment by SergioEstevao** [comment]
Yes those one are expected:

- The interface.storyboard warning will only be removed when we update all the WatchKit code to use SwiftUI
- The animation issue needs some extra investigation to see what is a good alternative that does not break anything
- The return warning is because we have compiler flag that disables checks when running on the simulator.

**Review by leandroalonso — APPROVED** [review]
Got it, we're good then!

**Pull request merged**
