### PR TITLE
Fix up next navigation items

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #

Please include a summary of the changes and the related issue.

## To test

- Start the app
- Clean UpNext items ( long press on the mini-player image and choose Close And Clear Up Next)
- Check that the navigation bar in clean of items ( Select )
- Go to the podcasts tab
- Open a podcast and add some items to the UpNext queue
- Switch to the UpNext tab
- Check that the navigation bar has the Select option
- Tap Select
- Choose some items and while they are selected
- Clean UpNext items ( long press on the mini-player image and choose Close And Clear Up Next)
- Check that the navigation bar updates correctly, it should show any actions

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/50">7.65 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — APPROVED** [review]
The mentioned testing steps works just as expected, however, for some themes the buttons are barely visible or not visible at all:

| Indigo | Classic |
| ----- | -------- |
| Simulator Screenshot - iPhone 15 - 2024-06-06 at 10 39 55 | Simulator Screenshot - iPhone 15 - 2024-06-06 at 10 43 13 |

**Comment by SergioEstevao** [comment]
> for some themes the buttons are barely visible or not visible at all

Great catch just updated the code to fix that if you want to give it another look

**Comment by leandroalonso** [comment]
Nice, just re-tested and now it's working just fine!

**Pull request merged**
