### PR TITLE
Categories Redesign: Modal picker

### PR DESCRIPTION
**Pull request by bjtitus**
Adds a bottom sheet modal picker to select additional categories not in the pills.

https://github.com/Automattic/pocket-casts-ios/assets/3250/db647d61-b50e-41e0-b5db-efb49fdaeec6

## To test

* Build using the Staging build configuration
* Ensure the `categoriesRedesign` flag is on
* * Navigate to the Discover tab
* Tap the "All Categories" pill
* Notice the Modal which appear
* Tap a category in the Modal
* Notice that the Discover screen changes to a Category list but the Category Pills remain at the top and properly animate
* Tap the X button to reset and navigate back to the original Discover page

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — CHANGES_REQUESTED** [review]
When using Indigo the title of the bottom sheet has a super low contrast:



@bjtitus if you add a preview to `CategoriesModalPicker` you can use `.previewWithAllThemes()` and this helps a lot when testing multiple themes. :)

**Comment by bjtitus** [comment]
> if you add a preview to CategoriesModalPicker you can use .previewWithAllThemes()

Nice! I switched to a different color. The color doesn't really change by theme but it's the same one used by `OptionsPickerRootController`.



There was also a bug with the cell pressed state which I fixed by manually recreating it using a `Button`. It turns out that using `listRowBackground` disables the cell pressed state with no modifier to re-enable it. 🙄 

Also bumped padding around to get it closer to the original designs.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/45">7.62</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by leandroalonso — APPROVED** [review]
@bjtitus I think it's not possible to make the bottom sheet expand when scrolling up, right? At least not easily. I think that would be a nice touch but not necessary, so good to go!

**Comment by bjtitus** [comment]
> I think it's not possible to make the bottom sheet expand when scrolling up, right?

It is! I added the `large` presentation detent and hid the grabber:

https://github.com/Automattic/pocket-casts-ios/assets/3250/b673543d-eab5-4765-bce3-54d256793dd3

**Pull request merged**
